In [ ]:
import re
import requests
from bs4 import BeautifulSoup
from tqdm import tqdm, tqdm_notebook

In [ ]:
key1 = '신한은행'
page = [ i for i in range(1, 4000, 10)]

Year = ['2020','2020','2021']
Month = ['01','02','03','04','05','06','07','08','09','10','11','12']
Day_S = ['1','6','11','16','21','26']
Day_E = ['5','10','15','20','25','31']

list_naver_news = [ ]
times = [ ]
titles = [ ]
links = [ ]
infos = [ ]

for year in Year:
  for month in Month:
    print(month)
    for i in range(0,1):
      Date_Start = year + '.' + month + '.' + Day_S[i]
      Date_End = year + '.' + month + '.' + Day_E[i]

      Date_Start_2 = year + month + Day_S[i]
      Date_End_2 = year + month + Day_E[i]

     # print(Date_Start, Date_End, Date_Start_2, Date_End_2)

      news_time = [ ] 
      news_title = [ ]
      news_info = [ ]

      for p in tqdm(page):
        
        url_news = 'https://search.naver.com/search.naver?where=news&sm=tab_pge&query='+key1+'&sort=2&photo=0&field=0&pd=3&ds=' + Date_Start + '&de=' + Date_End
        url_news = url_news + '&mynews=0&office_type=0&office_section_code=0&news_office_checked=&nso=so:r,p:from' + str(Date_Start_2) + 'to' + str(Date_End_2) + ',a:all&start=' + str(p)
                
        
        r = requests.get(url_news)
        soup = BeautifulSoup(r.text, 'html.parser')

        time = soup.body.find_all('span', attrs={'class':'info'}) 
        news_time = time

        title = soup.body.find_all('a', attrs={'class':'news_tit'}) 
        news_title = title

        info = soup.body.find_all('a', attrs={'class':'api_txt_lines dsc_txt_wrap'})
        news_info = info

        if len(news_title) > 0 :
          for j in range(len(news_title)): 
              times.append(news_time[j].text)
              titles.append(news_title[j].text)
              links.append( str(news_title[j]).split('<a class="news_tit" href=')[1].split('"')[1] )
              infos.append(news_info[j].text)
        else:
          break

      print(len(titles))
#      print(titles)
#Date_Start = '2019.01.01'
#Date_End = '2019.01.15'

#Date_Start_2 = '20190101'
#Date_End_2 = '20190115'

len(list_naver_news)

01

 17%|█▋        | 69/400 [01:31<07:19,  1.33s/it]

689
02

 22%|██▏       | 88/400 [01:50<06:31,  1.25s/it]

1568
03

 24%|██▍       | 96/400 [02:03<06:29,  1.28s/it]

2523
04

 46%|████▌     | 182/400 [03:49<04:34,  1.26s/it]

4342
05

100%|██████████| 400/400 [08:19<00:00,  1.25s/it]

8342
06

 64%|██████▎   | 254/400 [05:23<03:06,  1.28s/it]

10875
07

 92%|█████████▏| 366/400 [07:41<00:42,  1.26s/it]

14531
08

 87%|████████▋ | 349/400 [07:08<01:02,  1.23s/it]

18014
09

 70%|███████   | 280/400 [05:50<02:30,  1.25s/it]

20806
10

 82%|████████▏ | 329/400 [06:57<01:30,  1.27s/it]

24096
11

 32%|███▏      | 129/400 [02:41<05:39,  1.25s/it]

25379
12

 31%|███▏      | 125/400 [02:36<05:44,  1.25s/it]

26621

0

In [ ]:
import pandas as pd

df = pd.DataFrame({ 'time' : times, 'title' : titles, 'info' : infos, 'link' : links })
df.to_excel('크롤링(신한은행,2020추가).xlsx', encoding='utf-8-sig')

In [ ]:
df.to_excel('/content/drive/My Drive/Colab Notebooks/뉴스 크롤링/크롤링(신한은행,2020추가).xlsx')

In [ ]:
df

,time,title,info,link
0,2019.01.01.,[2019 재테크 기상도] 글로벌 성장 둔화 가속화…'마음의 여유' 필요할 때,"농협은행 WM연금부 김형리 차장은 ""변동성 관리 측면에서 보면 최근 옵션과 같은 파...",http://www.ajunews.com/view/20181224084732509
1,2019.01.01.,"김병원 농협회장 ""농협이 농업인의 영원한 동반자로 확실하게 자리매김하도록...","농협은행은 업계 최초로 현업과 IT, 외부업체가 한 곳에 모여 일하는 공간인 NH디...",http://www.kenews.co.kr/news/article.html?no=1...
2,2019.01.01.,"농민에겐 안정적 소득원, 지역사회엔 든든한 일자리 제공",아울러 NH농협은행 신토불이코너 역시 로컬푸드직매장으로 변경해 운영하는 방안도 세웠...,http://www.nongmin.com/article/ar_detail.htm?a...
3,2019.01.01.,“새해에는 해외여행 가고 싶어요”…원주 타종식,치악체육관에서 열렀으며 사랑ㆍ희망 편지쓰기 등 부대행사도 함께 펼쳐졌다. 현장에서는...,http://www.enewstoday.co.kr/news/articleView.h...
4,2019.01.01.,[경제 전문가 100명 설문조사]경제전문가 설문조사 참여자,(NH농협은행 강원영업본부장) 정진락(한국감정원 강원지원장) 정창훈(신용보증기금 춘...,http://www.kwnews.co.kr/view.asp?aid=218123100...
...,...,...,...,...
47633,2019.12.31.,군산시 상하수도 요금납부 전북은행과 농협은행 2곳으로 늘려,"군산시 상하수도 요금납부 고객전용 가상계좌가 2곳(전북은행, NH농협은행)으로 늘어...",http://www.sjbnews.com/news/articleView.html?i...
47634,2019.12.31.,"NH농협은행, 신규직원 280명 채용",NH농협은행이 미래 디지털 인재 확보와 함께 청년일자리 창출을 위해 하반기 190여...,http://www.sjbnews.com/news/articleView.html?i...
47635,2019.12.31.,"농협, 2020년 상반기 신규직원 310명 채용…31일부터 접수 시작",농협중앙회와 농협은행은 청년고용 확대 및 양질의 일자리 창출을 위하여 2020년 상...,http://www.enewstoday.co.kr/news/articleView.h...
47636,2019.12.31.,"농협은행 경남본부, M급·3급 직원 임용장 수여",NH농협은행 경남본부(본부장 김한술)는 M급·3급 직원들의 정기인사를 통해 신규 보...,http://www.gnnews.co.kr/news/articleView.html?...
47637,2019.12.31.,대전농협 본부장 이취임식,대전농협은 대전지역본부 윤상운 대전지역본부장과 강필규 NH농협은행 대전영업본부장 이...,http://www.cctoday.co.kr/news/articleView.html...